name: Build Gocron

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'v1.5.3'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up Go 1.15
        uses: actions/setup-go@v3
        with:
          go-version: "1.15"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: "recursive"

      - name: Get dependencies and build
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          sudo apt-get -y install build-essential
          go env -w GO111MODULE=on
          yarn config set ignore-engines true
          make install-vue
          make build-vue
          make statik
          bash ./package.sh -a 'arm64 amd64' -p 'linux' -v ${{ github.event.inputs.tag }}

      - name: Upload package files
        uses: actions/upload-artifact@v3
        with:
          name: gocron
          path: gocron*/**.tar.gz

      - name: Generate release txt
        run: |
          touch release.txt
          echo -e "**Version**: ${{ github.event.inputs.tag }}" >> release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          body_path: release.txt
          files: gocron*/**.tar.gz

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5
